### PR TITLE
Add support for calculating multiple items

### PR DESCRIPTION
**Pull request by Bmandk**
Implements https://github.com/GTNewHorizons/JustEnoughCalculation/issues/13

This feature allows players to add multiple items to the calculator. This is useful if players want to batch craft multiple items at the same time that all use the same components. 

For example, if a player wants to craft robot arms and conveyors, they will need several motors. Instead of having to calculate them by themselves, they can now do it in one go.

Here's a short video showing the feature in action with vanilla items.

https://github.com/user-attachments/assets/31f80228-e89d-4be6-ae33-a825aeec514a

### CODE REVIEW

**Comment by Caedis** [comment]
can you run the `spotlessApply` task and push the changes please?

**Comment by Bmandk** [comment]
Just pushed it, thanks

**Comment by Caedis** [comment]
Probably not going to like the wildcard import

**Comment by Bmandk** [comment]
Ah, must have been my IDE as it automatically handles that. I'll revert that part so it only imports what's needed.

**Comment by Bmandk** [comment]
Third time's the charm

**Comment by Bmandk** [comment]
Fixing...

**Comment by Caedis** [comment]
If it fails again, i should be able to push changes to it

**Comment by Bmandk** [comment]
Yeah this time it seems to have failed due to a problem I also had locally, but I found a workaround by replacing 

```
        clientSide = Tags.GROUPNAME + ".network.ClientProxy",
        serverSide = Tags.GROUPNAME + ".network.CommonProxy")
```
with
```
        clientSide = "me.towdium.jecalculation.network.ClientProxy",
        serverSide = "me.towdium.jecalculation.network.CommonProxy")
```

in `JustEnoughCalculations.java`... I'm not sure whether this is intended, since it's also what's on master currently.

**Comment by Caedis** [comment]
I got it

**Review by Caedis — APPROVED** [review]
Works well in the full pack (latest nightlies). Good job

**Comment by Bmandk** [comment]
Thanks for the help!

**Pull request merged**
